# This file was generated by GoReleaser. DO NOT EDIT.
cask "taggar" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "423c4f9eacf233bd66a39da2ca91dbfd76129ddcd62a87c08298b39589faf651"
      url "https://github.com/m4rc3l05/taggar/releases/download/v#{version}/taggar_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5bca810b1d44f4c1b94a1afd468738e19226dfb2542cae1d7777b178fb7ad5cb"
      url "https://github.com/m4rc3l05/taggar/releases/download/v#{version}/taggar_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8df9c607ef53d88f28c5b6a07c5e887fa5f20cae3010843131dabdb7cdbd1b37"
      url "https://github.com/m4rc3l05/taggar/releases/download/v#{version}/taggar_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d46dc0899003c5b44af15d3dff0cffe950955a9488f409d0df48df56b922817f"
      url "https://github.com/m4rc3l05/taggar/releases/download/v#{version}/taggar_Linux_arm64.tar.gz"
    end
  end

  name "taggar"
  desc "Media tagging viewer & editor"
  homepage "https://github.com/M4RC3L05/taggar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taggar"

  generate_completions_from_executable "taggar", "completion",
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
