# This file was generated by GoReleaser. DO NOT EDIT.
cask "taggar" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3a759c9ff57c4af963aa33310c0a8a7d541e4ca0ae1573091b400d5f08175617"
      url "https://github.com/m4rc3l05/taggar/releases/download/v#{version}/taggar_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3535a968750bef281a8b03f92649272e13fe8c26dde40f367242772b7be60b73"
      url "https://github.com/m4rc3l05/taggar/releases/download/v#{version}/taggar_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "91d9b03f7a3bb2c544a124571c8b9287fe0f734b8b912cb366a8217101993728"
      url "https://github.com/m4rc3l05/taggar/releases/download/v#{version}/taggar_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ddce32bc0882827295986cec2e70235524b168126491541b9fcb5b9d826a2bd7"
      url "https://github.com/m4rc3l05/taggar/releases/download/v#{version}/taggar_Linux_arm64.tar.gz"
    end
  end

  name "taggar"
  desc "Media tagging viewer & editor"
  homepage "https://github.com/M4RC3L05/taggar"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taggar"

  generate_completions_from_executable "taggar", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

end
